[tool.poetry]
name = "bot"
version = "0.1.0"
description = ""
authors = ["Wei-Cheng Pan <legnaleurc@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0.1"
SQLAlchemy = "^2.0.29"
tornado = "^4"
"wcpan.telegram" = "^0.3.0.dev7"
python-telegram-bot = "^21.0.1"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
